classdef Chemele
    % CHEMELE: An object storing the names of all chemical elements
    %
    %   Syntax:
    %      chemelist = Chemele.valelename;
    %
    %   Example:
    %      Chemele.valelename
    %
    %See also Chemformula, Glycan, Aminoacid, Protease, Modification, mzXML

    
    %Author: Gang Liu
    %Date: 1/19/2015
    
   properties (Constant)
        valelename={'H','He','Li','Be','B','C','N','O','F','Ne','Na','Mg','Al',...
            'Si','P','S','Cl','Ar','K','Ca','Sc','Ti','V','Cr','Mn','Fe','Co',...
            'Ni','Cu','Zn','Ga','Ge','As','Se','Br','Kr','Rb','Sr','Y','Zr',...
            'Nb','Mo','Tc','Rn','Rh','Pd','Ag','Cd','In','Sn','Sb','Te',...
            'I','Xe','Cs','Ba','La','Ce','Pr','Nd','Pm','Sm','Eu','Gd','Tb',...
            'Dy','Ho','Er','Tm','Yb','Lu','Hf','Ta','W','Re','Os','Ir','Pt',...
            'Au','Hg','Tl','Pb','Bi','Po','At','Rn','Fr','Ra','Ac','Th','Pa',...
            'U','Np','Pu','Am','Cm','Bk','Cf','Es','Fm','Md','No','Lr','Rf',...
            'Db','Sg','Bh','Hs','Mt','Ds','Rg','Cn','Uut','Fl','Uup','Lv',...
            'Uus','Uuo'};
    end 
end