function hit=scoreAllSpectra_spmd(varargin)
%SCOREALLSPECTRA_SPMD: Score all MS2 spectra against glycopeptide library.
%
% Syntax:
%    hit = scoreAllSpectra_spmd(Pepfile,dtafilesDirectory,fragMod,MS1tol,MS1toUnit,...
%           MS2tol,MS2tolUnit,CSVOutputDir,CSVfilename,MaxLag,CutOffMed,FracMax,...
%           nmFrag,npFrag,ngFrag,selectPeak)
%
%    hit = scoreAllSpectra_spmd(Pepfile,dtafilesDirectory,fragMod,MS1tol,MS1toUnit,...
%           MS2tol,MS2tolUnit,CSVOutputDir,CSVfilename,MaxLag,CutOffMed,FracMax,...
%           nmFrag,npFrag,ngFrag,selectPeak,dispProgress)
%
%    hit = scoreAllSpectra_spmd(Pepfile,mzxmlfileDirectory,fragMod,MS1tol,MS1toUnit,...
%           MS2tol,MS2tolUnit,CSVOutputDir,CSVfilename,MaxLag,CutOffMed,FracMax,...
%           nmFrag,ngFrag,npFrag,selectPeak,dispProgress,mzxmlfilename)
%
% Input:
%    Pepfile: Theoretical peptide list generated by digestSGP.m
%    dtafilesDirectory: DTA file storage location
%    mzxmlfileDirectory: mzXML file storage location
%    fragMod: 'CID', 'HCD', 'ETD', 'CIDSpecial', 'HCDSpecial', 'ETDSpecial' or 'none'
%    MS1tol, MS1tolUnit: number and units either 'ppm' or 'Da'
%    MS2tol, MS2tolUnit: number and units either 'ppm' or 'Da'
%    CSVOutputDir, CSVfilename: Output directory and CSV file name
%    maxlag:    parameter used for Xcorr
%    CutOffMed, FractMax: Parameters used for PolishSpectra
%    nmFrag, ngFrag and npFrag: used in case of CID/HCD/ETDSpecial
%    selectPeak: glycan signature peaks or other peaks of interest
%    mzxmlfilename: mzXML file name
%
% Output: 
%    hit: score results
%    Output file with hits and scores tabulated
% 
% Example:
%   glycopatroot = 'c:\glycopat\'; % replace ¡°c:\glyocpat¡¯ with glycopat installation directory 
%   pepfile= 'digestedfetuin_Nglycanonly.txt ';
%   xmlfilepath = fullfile(glycopatroot, 'toolbox', 'test', 'data', 'mzxml');
%   pepfilefullname = fullfile(xmlfilepath,pepfile);
%   mzxmlfilename = 'fetuin_test.mzXML';
%   fragMode = 'AUTO';
%   MS1tol = 10.000000;
%   MS1tolUnit = 'ppm';
%   MS2tol = 1.000000;
%   MS2tolUnit = 'Da';
%   OutputDir = xmlfilepath;
%   OutCSVname = 'testscore.csv';
%   maxlag = 50;
%   CutOffMed = 2.000000;
%   FracMax = 0.020000;
%   nmFrag = 0;
%   npFrag = 2;
%   ngFrag = 0;
%   selectPeak =[163.1,292.1,366,454.1,657.2];
%   calchit = scoreAllSpectra_spmd(pepfilefullname,xmlfilepath,fragMode,MS1tol,MS1tolUnit,MS2tol, ...
%     MS2tolUnit,OutputDir,OutCSVname,maxlag,CutOffMed,FracMax,nmFrag,npFrag,ngFrag, ...
%     selectPeak,false,mzxmlfilename);
% 
% Children functions: GetData, score1File, glypepMW, struct2csv, isoDist
%
%See also scoreAllSpectra, scoreAllSpectra_parfor.

% Author: Gang Liu, Sriram Neelamegham.
% Date Lastly Updated: 12/11/14

narginchk(16,18);
Pepfile=varargin{1};
DataDirectory=varargin{2};
fragMode=varargin{3};
MS1tol=varargin{4};
MS1tolUnit=varargin{5};
MS2tol=varargin{6};
if(~isnumeric(MS1tol)||~isnumeric(MS2tol))
    error('MATLAB:GLYCOPAT:ERRORINPUT','MS1/2 TOLERANCE INPUT TYPE ERROR');
end
MS2tolUnit=varargin{7};
OutputDir=varargin{8};
Outfname=varargin{9};
maxlag=varargin{10};
CutOffMed=varargin{11};
FracMax=varargin{12};
nmFrag=varargin{13};
npFrag=varargin{14};
ngFrag=varargin{15};
selectPeak=varargin{16};
if(nargin>=17)
  dispprogress=varargin{17};
else
  dispprogress = false;
end

if(nargin==18)
    mzxmlfilename = varargin{18};
    xmlfullfilename = fullfile(DataDirectory,mzxmlfilename);
    usemzxml = 1;
else
    mzxmlfilename = '';
    xmlfullfilename = '';
    usemzxml = 0;
end

nFrag       = [nmFrag,ngFrag,npFrag];
param       = [maxlag,CutOffMed,FracMax];
fullOutName = fullfile(OutputDir,Outfname);

%% read ms data and other info. from DTA or mzXML file
if(usemzxml)
    [Spectra,Scan,z,MH,actmethod,mslevel]= getMSInfoFromMZXML(DataDirectory,mzxmlfilename,fragMode);
else
    [Spectra,Scan,z,MH,actmethod]= getMSInfoFromDTA(DataDirectory,mzxmlfilename);
    mslevel = zeros(1:length(Spectra));
    parfor i =1:length(Spectra)
        mslevel(i) = 2;
    end
end
numSpectra = length(Spectra);

%% Read list of theoretically possible products
fileID = fopen(Pepfile);
if(fileID==-1)
    error('MATLAB:GlycoPAT:OPENFILEERROR','FILE DOES NOT EXIST');
end
pepData = textscan(fileID,'%s%*[^\n]');
fclose(fileID);
[nProtein,startPep,endPep,headerinfo]=ParsePeptideCell(pepData{1});
spectralengthfilter = 10;
PepNames            = {};
ProteinIDs          = [];
for k = 1 : nProtein
    singlePepNames  =  pepData{1}(startPep(k):endPep(k));
    PepNames        =  [PepNames;singlePepNames];
    singleProtIDs   =  ones(length(singlePepNames),1)*k;
    ProteinIDs      =  [ProteinIDs;singleProtIDs];
end

%% Calculte Glycopeptide Mass
disp('calculating isotopic mass');
PepMS1 = zeros(length(PepNames),1);
PepMost = zeros(length(PepNames),1);
parfor i = 1 : length(PepNames)
    %[PepMS1(i,1),PepMost(i,1),~]=glypepformula(char(PepNames(i)));
    PepMS1(i,1)=glypepMW(char(PepNames(i)));
end

%% construct array
MSSpectra = repmat(struct('spectra',[],'mslevel',[],...
    'actmethod',[],'Scan',[],'MH',[],'z',[]),1,numSpectra);

parfor i = 1 : numSpectra
    MSSpectra(i).Spectra   = Spectra{i};
    MSSpectra(i).mslevel   = mslevel(i);
    MSSpectra(i).actmethod = actmethod{i};
    MSSpectra(i).Scan      = Scan(i);
    MSSpectra(i).MH        = MH(i);
    MSSpectra(i).z         = z(i);
end

%% distribute the spectra array
distspectra = distributed(MSSpectra);
spmd
    localSpectra         = getLocalPart(distspectra);
    hitsingle            = scorelocalspectra(localSpectra,usemzxml,...
        spectralengthfilter,PepMS1,PepMost,PepNames,headerinfo,...
        MS1tol,MS1tolUnit,MS2tol,MS2tolUnit,param,nFrag,selectPeak,ProteinIDs);
end

% merge all worker's result
hit=[];
for i = 1 : numel(hitsingle)
    hit=[hit;hitsingle{i}'];
end
hit = hit';

% nummatch = length(matchedMS2);
% fprintf(1,' the total number of match is: %i\n',nummatch);
% spmd
%    codistr = codistributor1d(2, ...
%                      codistributor1d.unsetPartition, [1,nummatch]); 
%    distmatchedMS2 = codistributed(matchedMS2,codistr);
%    localmatchedMS2    = getLocalPart(distmatchedMS2);
%    localspectrascores = scorelocalspectra(localmatchedMS2,scoreoptobj,...
%        outputhtmlfile,htmlpath,outputoption);
%    globalspectrascores = codistributed.build(localspectrascores, codistr);
% end
%     
% spectrascores = gather(globalspectrascores);    

% assign the parameter to csvheaderinfo.
csvheaderinfo = struct('Pepfile',Pepfile,'DataDirectory',DataDirectory,...
    'xmlfullfilename',xmlfullfilename,'fragMode',fragMode,'MS1tol',MS1tol,...
    'MS1tolUnit',MS1tolUnit,'MS2tol',MS2tol,'MS2tolUnit',MS2tolUnit,...
    'nFrag',nFrag,'maxlag',maxlag,'CutOffMed',CutOffMed,'FracMax'....
    ,FracMax,'selectPeak',selectPeak);

% output the results to a csv file
scoreCSVwrite(csvheaderinfo,hit,fullOutName);
end

function hit = scorelocalspectra(localSpectra,usemzxml,...
    spectralengthfilter,PepMS1,PepMost,PepNames,headerinfo,...
    MS1tol,MS1tolUnit,MS2tol,MS2tolUnit,param,nFrag,selectPeak,ProteinIDs)
%score spactra against the database
hitCount=0;
hit=[];

for i = 1 : length(localSpectra)
    scannum = localSpectra(i).Scan;
    ismslevel2 = localSpectra(i).mslevel~=2;
    if(usemzxml==1)&& (ismslevel2);
        continue;
    end
    
    if(length(localSpectra(i).Spectra)<=spectralengthfilter)
        continue;
    end
    
    if(strcmpi(localSpectra(i).actmethod,'pass'))
        continue;
    end
    
    % check if the spectra has fewer than 10 peaks
    SmallGlyPep =[];
    
    if (strcmpi(MS1tolUnit,'ppm'))
        mhMonoDiff = abs(PepMS1(:,1)+1.007825032-localSpectra(i).MH)...
            <=MS1tol/1e6*localSpectra(i).MH;
        if any(mhMonoDiff)
            list=find(mhMonoDiff);
            SmallGlyPep=PepNames(list);   % find the peptide of interest, there may be more than one
            Mono=PepMS1(list);
            Most=PepMost(list);
        end
    elseif(strcmpi(MS1tolUnit,'Da'))
        mhMonoDiffDa = abs(PepMS1(:,1)+1.007825032-localSpectra(i).MH)<=MS1tol;
        if any(mhMonoDiffDa) % if tolerance is given in Da units
            list=find(mhMonoDiffDa);
            SmallGlyPep=PepNames(list);   % find the peptide of interest, there may be more than one
            Mono=PepMS1(list);
            Most=PepMost(list);
        end
    else
        error('MATLAB:GlycoPAT:ERRORUNIT','INCORRECT UNIT FOR MS1 TOL');
    end
    
    % display scan number and possible hits
    i
    fprintf(1,'scan number: %i\n',scannum);
    fprintf(1,'possible glycopeptide:\n');
    SmallGlyPep
    ithzA = localSpectra(i).z;
    ithspectra = localSpectra(i).Spectra;
    ithactmethod = localSpectra(i).actmethod;
    ithMH = localSpectra(i).MH;
    for j=1:length(SmallGlyPep)
        spectrascores(j) = score1Spectrum(ithspectra,SmallGlyPep(j),...
            ithactmethod,MS2tol,MS2tolUnit,param,nFrag,selectPeak,ithzA,ithMH,1);
    end
    
    for j=1:length(SmallGlyPep)
        hitCount=hitCount+1;
        hit(hitCount).protein    = headerinfo{ProteinIDs(list(j))};
        hit(hitCount).Scan       = scannum;
        hit(hitCount).Expt       = localSpectra(i).MH-1.0078246;
        hit(hitCount).Mono       = Mono(j);
        hit(hitCount).Most       = Most(j);
        hit(hitCount).charge     = ithzA;
        hit(hitCount).sgp        = SmallGlyPep{j};
        hit(hitCount).fragmode   = ithactmethod;
        hit(hitCount).peakLag    =  spectrascores(j).peakLag;
        hit(hitCount).htCenter   =  spectrascores(j).htCenter;
        hit(hitCount).htAvg      =  spectrascores(j).htAvg;
        hit(hitCount).percentIonMatch = spectrascores(j).percentIonMatch;
        hit(hitCount).Pvalue     = spectrascores(j).Pvalue;
        hit(hitCount).decoyRatio = spectrascores(j).decoyRatioP;
        hit(hitCount).Top10      = spectrascores(j).Top10;
        hit(hitCount).selectPeak = spectrascores(j).foundSelectPeak;
        hit(hitCount).nmFrag     = spectrascores(j).nFrag(1);
        hit(hitCount).ngFrag           = spectrascores(j).nFrag(2);
        hit(hitCount).npFrag           = spectrascores(j).nFrag(3);
        hit(hitCount).enscore          = spectrascores(j).enscore;
        hit(hitCount).fdrdecoyenscore  = spectrascores(j).fdrdecoyenscore;
    end
end

% convert select peak to string
for i = 1 : length(hit)
    peakstring='';
    for j=1:length(hit(i).selectPeak)
        peakstring=[peakstring,num2str(hit(i).selectPeak(j)),'*'];
    end
    hit(i).selectPeak = peakstring;
end
end

function [Spectra,Scan,z,MH,actmethod,mslevel]= getMSInfoFromMZXML(...
    DataDirectory,mzxmlfilename,fragMode)
xmlfullfilename = fullfile(DataDirectory,mzxmlfilename);
mzXMLobj        = mzXML(xmlfullfilename,0,'memsave');
Scan            = mzXMLobj.retrieveScanNum;
z               = mzXMLobj.retrievezCharge;
Mz              = mzXMLobj.retrieveMz;
MH              = Mz.*z - (z-1)*1.007825032;
numSpectra      = length(Scan);
Spectra         = cell(numSpectra,1);
actmethodfromxml = cell(numSpectra,1);
mslevel          = zeros(numSpectra,1);
for i = 1 : numSpectra
    if(~isempty(mzXMLobj.mzxmljava.rap(i)))
        Spectra{i}          = mzXMLobj.retrieveMSSpectra(i);
        actmethodfromxml{i} = mzXMLobj.retrieveActMethod(i);
        mslevel(i)          = mzXMLobj.mzxmljava.rap(i).getMsLevel;
    else
        Spectra{i} =[];
        actmethodfromxml{i}= '';
        mslevel(i) =1;
    end
end

actmethod = getMSActMethod(actmethodfromxml,fragMode,numSpectra);
end

function actmethod = getMSActMethod(actmethodfromxml,fragMode,numSpectra)

actmethod = cell(1,numSpectra);
for i = 1 : numSpectra
    % check if the spectra is the right spectra for the fragmentation
    % mode
    if(strcmpi(fragMode,'ETD')||strcmpi(fragMode,'ETDSpecial'))
        actmethod{i} = 'ETD';
    elseif(strcmpi(fragMode,'CID')||strcmpi(fragMode,'CIDSpecial'))
        actmethod{i} = 'CID' ;
    elseif(strcmpi(fragMode,'HCD')||strcmpi(fragMode,'HCDSpecial'))
        actmethod{i} = 'HCD';
    elseif(strcmpi(fragMode,'Auto'))
        actmethod{i} = 'Auto';
    else
        error('MATLAB:GlycoPAT:ERRORFRAGMENT','ERROR IN FRAGEMENTATION MODE');
    end
    
    if(strcmpi(actmethod{i},'auto'))
        actmetfromdata = actmethodfromxml{i};
        if(~isempty(strfind(upper(actmetfromdata),'ETD')))
            actmethod{i} ='ETD';
        elseif(~isempty(strfind(upper(actmetfromdata),'CID')))
            actmethod{i} ='CID';
        elseif(~isempty(strfind(upper(actmetfromdata),'HCD')))
            actmethod{i} ='HCD';
        else
            actmethod{i} ='pass';
        end
    elseif(~isempty(actmethod{i}))
        actmetfromdata = actmethodfromxml{i};
        if(isempty(strfind(upper(actmetfromdata),upper(actmethod{i}))))
            actmethod{i} ='pass';
        else
            actmethod{i} = fragMode;
        end
    else
        error('MATLAB:GlycoPAT:ERRORACTIVATION','ERROR IN ACTIVATION METHOD');
    end
end

end

function [Spectra,Scan,z,MH,actmethod]= getMSInfoFromDTA(DataDirectory,fragMode)
files        = dir(DataDirectory);               % reads directory and puts it in a matlab structure
filename     = {files(~[files.isdir]).name}'; % reads filename from structure and puts in cell, excluding directory elements
tempfilename = [];
for i=1:length(filename)
    [pathstr,name,ext] = fileparts(char(filename(i)));
    if regexp(ext,'dta')   % includes only files that contain the text 'dta'
        tempfilename=[tempfilename,filename(i)];
    end
end
filename   = tempfilename';
filestring = char(filename);              % converts cell array to string array
numSpectra = length(filename);
MH  = zeros(1,numSpectra);
z   = zeros(1,numSpectra);
Spectra = cell(1,numSpectra);
actmethod = cell(1,numSpectra);
for i = 1 : numSpectra
    ithFile    = filestring(i,:);
    dots       = strfind(ithFile,'.');
    Scan(i)    = str2double(ithFile(dots(1)+1:dots(2)-1));  % Reads all Scan numbers is a directory and places it in array Scan
    xfile      = fullfile(DataDirectory,filestring(i,:));
    [MH(i),z(i),Spectra{i}] = GetData(xfile);   % read MS data from DTA files
end

for i =1 : numSpectra
    actmethod{i} = fragMode;
end

end