function [scan,z,Mz,spectra]= getScanZMSpectra(obj)
% GETSCANZMSPECTRA: Retrieve MS2 precursor scan data from an mzXML object
%  
% Syntax:
% [scan,z,Mz,spectra]= getScanZMSpectra(mzxmlobj)
%
% Input:
% mzxlobj: an mzXML object acquired from mzXML file
%
% Output:
% scan: 1 x n matrix containing scan numbers
% z: 1 x n matrix containing precursor charge state
% Mz: 1 x n matrix containing precursor m/z value
% spectra: 1 x n cell array each containing 
% 
% Note:
% mzXML object is generated by loading mzXML file using
% "mzXML(mzxmlfilename)"
%
% Example:
%    mzXMLobj = mzXML('demofetuin.mzXML');
%   [scan,z,mz,spectra] = mzXMLobj.getScanZMSpectra;
%
% See also: mzXML.

% Author: Gang Liu
% Date Lastly Updated: 08/05/15
ms2scan = obj.getMSScan('mslevel',2); 
for i = 1 : length(ms2scan)
   scan(i)    = ms2scan{i}.scannum;
   z(i)       = ms2scan{i}.precursorCharge;
   spectra{i} = ms2scan{i}.msintensitylist;
   Mz(i)      = ms2scan{i}.precursorMz;
end        

end